### ISSUE TITLE
Error after latest release

### ISSUE THREAD

**Issue by supriyopaul** [deep-compute/basescript#59]
@Rajendra-R 

Error:
![image](https://user-images.githubusercontent.com/33823698/37890086-d19a1cf2-30ec-11e8-9dda-c582b93d96f8.png)
Basescript version:
![image](https://user-images.githubusercontent.com/33823698/37890162-1ef00c96-30ed-11e8-921a-ba426172ab74.png)

Code:
![image](https://user-images.githubusercontent.com/33823698/37890246-74b2270e-30ed-11e8-93d0-64bcdfa3f076.png)

**Comment by supriyopaul** [comment]
Same code on previous basescript version:
![image](https://user-images.githubusercontent.com/33823698/37890537-8506a5c0-30ee-11e8-9f3d-0e1bf97f5db5.png)

**Comment by ghost** [comment]
@supriyopaul 
* You have to modify the `serverstats` code based on new `Basescript` version.

**Comment by supriyopaul** [comment]
And where is that doccumented?

**Comment by ghost** [comment]
@supriyopaul 
* We are getting this error in new `Basescript` version because of new feature metric-grouping logic, In your `serverstat` metric there was a dictionary inside it because of that we are getting this error.
* We will update the `Basescript` according to your use case as well.
* For now, you can run your `serverstats` code with new `Basecript` version by saying without metric grouping shown given below.
* If you run in a debug mode we will not be grouping the `metrics`
* We will update the readme.
![screen shot 2018-03-26 at 12 34 24 pm](https://user-images.githubusercontent.com/16955073/37891702-db5dd7a0-30f2-11e8-87d0-6e81d03212e4.png)

**Comment by prashanthellina** [comment]
@Rajendra-R Please let me know if you need to discuss on how to handle this.

**Comment by ghost** [comment]
Sure @prashanthellina When I start working on this we will discuss with you.

**Comment by ghost** [comment]
@supriyopaul We are tracking this issue at https://github.com/deep-compute/basescript/issues/62

**Comment by ghost** [comment]
* We are tracking this issue at some other ticket which is already linked to this, so we can close this ticket.
